### ISSUE TITLE
SyntaxError 

### ISSUE THREAD

**Issue by GuyyaReiki** [InnateAlpaca/BedrockBridge#5] opened 2024-04-25 11:13 UTC
[Scripting] Plugin [Bedrock-Bridge v1.3.9 - 1.3.9] - [main.js] ran with error: [SyntaxError: Could not find export 'Vector' in module '@minecraft/server']

**Comment by InnateAlpaca** [comment] 2024-04-25 15:43
Hello, can you provide more context about when this error happened? Was it at startup or later on?

**Comment by InnateAlpaca** [comment] 2024-04-25 16:34
Alright, the issue was caused by a bridge-plugins: "Basic Warps". Please replace the plugin files with the fixed one which we published today [on github](https://github.com/InnateAlpaca/BedrockBridge/tree/main/bridge_plugins/basicWarps)

**Comment by GuyyaReiki** [comment] 2024-04-26 01:14
ok thx

**Closed** 2024-04-26 07:40 UTC
Labels: bug
